- hosts: all
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Verificar si Docker está instalado
      shell: |
        if ! command -v docker &> /dev/null; then
          curl -fsSL https://get.docker.com | bash;
        fi

    - name: Asegurarse de que Docker Compose esté instalado
      shell: |
        if ! command -v docker-compose &> /dev/null; then
          curl -SL https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose;
          chmod +x /usr/local/bin/docker-compose;
        fi

    - name: Copiar archivo docker-compose.yml al servidor
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copiar archivo docker-compose.yml al servidor
      copy:
        src: ../.env
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Detener ejecucion de docker
      shell: |
        cd /home/ubuntu
        docker-compose down

    - name: Ejecutar docker-compose up
      shell: |
        cd /home/ubuntu
        docker-compose pull

    - name: Ejecutar docker-compose up
      shell: |
        cd /home/ubuntu
        docker-compose up -d